### ISSUE TITLE
WCL Framework File for Pascal

### ISSUE THREAD

**Issue by aryanpate18** [btframework/WCL-Lazarus-Demos#1]
Hello,

I've been trying to use the WCL library (VCL demo version) with Lazarus . However, I'm encountering an issue where the necessary Pascal files (`.pas` or `.ppu`) are missing in the `Common` and `Communication` folders of the downloaded demo library. This absence is preventing me from compiling the projects as described. Could you provide guidance on where to find these files or how to proceed with the setup? 

Thank you for your assistance!

**Comment by btframework** [comment]
The repository has been updated. Now it includes precompiled libraries for Lazarus 3.4 with FPC 3.2.2
